#!/usr/bin/env bash
# ─── download_tf.sh ─────────────────────────────────────────────────────────────
# Generates a TF tree PDF inside the g1_slam Docker container on the G1 robot,
# then copies it back to this local machine.
#
# Usage:
#   ./download_tf.sh
# ──────────────────────────────────────────────────────────────────────────────
set -euo pipefail

# ── Configuration ─────────────────────────────────────────────────────────────
SSH_USER="rc"
SSH_HOST="35.232.79.9"
SSH_PASS=""
SSH_KEY="./robotic_crew_rsa_gcp"
DOCKER_CONTAINER="g1_sim_controller"

# Directory on the remote (SSH) machine where TF PDFs are temporarily stored
REMOTE_TF_DIR="/home/rc/g1_sim_tfs"

# Path inside the Docker container where the PDF is generated
CONTAINER_TF_DIR="/tmp/tfs"

# Local directory on the host computer where TF PDFs are copied to
LOCAL_TF_DIR="$(cd "$(dirname "$0")" && pwd)/tfs"

echo "╔══════════════════════════════════════════════════════════════╗"
echo "║             TF Tree PDF Download Script                    ║"
echo "╠══════════════════════════════════════════════════════════════╣"
echo "║  Remote:    ${SSH_USER}@${SSH_HOST}"
echo "║  Container: ${DOCKER_CONTAINER}"
echo "║  Local dir:  ${LOCAL_TF_DIR}"
echo "╚══════════════════════════════════════════════════════════════╝"
echo ""

# Helper: run a command on the remote machine via SSH
ssh_cmd() {
    ssh -o StrictHostKeyChecking=no \
        -i "${SSH_KEY}" \
        "${SSH_USER}@${SSH_HOST}" "$@"
}

# Helper: copy files from the remote machine using scp
scp_from() {
    scp -o StrictHostKeyChecking=no \
        -i "${SSH_KEY}" \
        "$1" "$2"
}

# ── Step 1: Generate TF tree PDF inside the Docker container ──────────────────
echo "▶ [1/4] Generating TF tree PDF inside container..."
ssh_cmd "docker exec ${DOCKER_CONTAINER} bash -c '\
    mkdir -p ${CONTAINER_TF_DIR} && \
    cd ${CONTAINER_TF_DIR} && \
    source /opt/ros/humble/setup.bash && \
    [ -f /ros_ws/install/setup.bash ] && source /ros_ws/install/setup.bash; \
    ros2 run tf2_tools view_frames \
'"

echo "   ✔ TF tree PDF generated inside container."

# ── Step 2: Copy PDF from Docker container to the remote host ───────────────
echo "▶ [2/4] Copying PDF from container to remote host..."
ssh_cmd "mkdir -p ${REMOTE_TF_DIR} && docker cp ${DOCKER_CONTAINER}:${CONTAINER_TF_DIR}/. ${REMOTE_TF_DIR}/"
echo "   ✔ PDF copied to remote host: ${REMOTE_TF_DIR}"

# ── Step 3: Copy PDF from the remote host to the local machine ─────────────
echo "▶ [3/4] Downloading PDF to local machine..."
mkdir -p "${LOCAL_TF_DIR}"

# Files generated by view_frames look like frames_2024-03-31_22.21.36.pdf
# We copy all .pdf files found in that temporary directory
scp_from "${SSH_USER}@${SSH_HOST}:${REMOTE_TF_DIR}/*.pdf" "${LOCAL_TF_DIR}/"

# ── Step 4: Cleanup ───────────────────────────────────────────────────────────
echo "▶ [4/4] Cleaning up temporary files on remote host..."
ssh_cmd "rm -rf ${REMOTE_TF_DIR}/*.pdf"
ssh_cmd "docker exec ${DOCKER_CONTAINER} rm -rf ${CONTAINER_TF_DIR}/*.pdf"

echo ""
echo "═══════════════════════════════════════════════════════════════"
echo " ✅  TF Tree PDF downloaded successfully!"
echo ""
echo " Local files in ${LOCAL_TF_DIR}:"
ls -lh "${LOCAL_TF_DIR}"/*.pdf 2>/dev/null || echo "   --- no files found ---"
echo "═══════════════════════════════════════════════════════════════"
